### ISSUE TITLE
Cross compilation scala 2.13

### ISSUE THREAD

**Issue by lodamar** [yongjiaw/datacrafts#4]
We're using this useful lib in one of our project. We've migrated to scala 2.13 and we noticed this seems to be no longer maintained. We're thinking about forking it and republishing with cross compilation, but there's no license so according to github.
> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

Is it possible to add a license or change ownership? Thanks!

**Comment by yongjiaw** [comment]
Glad to hear it's useful for your project. I'll find a time to add license to this repo. Probably the MIT license, let me know your thought.

**Comment by lodamar** [comment]
> Glad to hear it's useful for your project. I'll find a time to add license to this repo. Probably the MIT license, let me know your thought.

Should be quite easy to add a licence: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

MIT license would be perfect, thanks

**Comment by lodamar** [comment]
License added, thanks
